# Generated by Django 4.1.5 on 2023-01-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prénom', models.CharField(max_length=128)),
                ('numéro', models.IntegerField(max_length=10)),
                ('adresse_email', models.CharField(max_length=250)),
            ],
        ),
    ]
